### PR TITLE
Class-based C++ API

### PR DESCRIPTION
**Pull request by ceriottm**
Use a SphericalHarmonics class to define the C++ interface.

### CODE REVIEW

**Comment by Luthaf** [comment]
TODO before merging:

- [ ] check documentation

**Comment by ceriottm** [comment]
> This is mostly fine for me.
> 
> Now that we hide the prefactors, we don't need to group everything in two objects, and we could have separate class members for different prefactors/buffers, which would increase readability (especially compared to the paper). But we can change this later!

Actually I tried this - I had even made a type holding `c,s,z` and used it for the buffer - but it was leading to noticeable slowdown of the calculation. Go figure.

**Comment by frostedoyster** [comment]
Documentation (for reference): https://sphericart--7.org.readthedocs.build/en/7/

**Comment by Luthaf** [comment]
From @ceriottm in https://github.com/lab-cosmo/scikit-matter/pull/171

> Only problem remaining: I noticed that the torch API documentation gets generated locally, but not on readthedocs. @Luthaf can you help? Then I'd merge so we can move to CUDA and start engaging external devs.

I'll give this a look tomorrow!

**Comment by ceriottm** [comment]
Only problem remaining: I noticed that the torch API documentation gets generated locally, but not on readthedocs. @Luthaf can you help? Then I'd merge so we can move to CUDA and start engaging external devs.

**Comment by ceriottm** [comment]
> From @ceriottm in [lab-cosmo/scikit-matter#171](https://github.com/lab-cosmo/scikit-matter/pull/171)
> 
> > Only problem remaining: I noticed that the torch API documentation gets generated locally, but not on readthedocs. @Luthaf can you help? Then I'd merge so we can move to CUDA and start engaging external devs.
> 
> I'll give this a look tomorrow!

Yeah sorry wrong repo ^_^

**Comment by frostedoyster** [comment]
Generating documentation for torch requires the torch build to succeed on readthedocs, but it was broken so I disabled it. I assumed @Luthaf was working on it on the other branch. You'll need to uncomment the torch build in .readthedocs.yml and then fix the issues with the build

**Comment by Luthaf** [comment]
Seems to be working with the CPU version of torch!

**Pull request merged**
