### PR TITLE
Integrate `sphericart_cuda` into JAX

### PR DESCRIPTION
**Pull request by frostedoyster**
CUDA support for `sphericart-jax`

### CODE REVIEW

**Comment by frostedoyster** [comment]
Documentation preview: https://sphericart--93.org.readthedocs.build/en/93/

**Comment by frostedoyster** [comment]
Closing and re-opening as an attempt to trigger the CSCS tests

**Comment by frostedoyster** [comment]
@nickjbrowning and I came to the conclusion that the best thing to do is to pass around the Python value of `normalized` just like we do with `l_max_c`. Working on it

**Comment by Luthaf** [comment]
Could you rebase & squash this branch? Happy to help you do this!

**Pull request merged**
