### PR TITLE
Added caching of the sphericart class

### PR DESCRIPTION
**Pull request by ceriottm**
As the title says - the C++ class gets cached to avoid recomputing prefactors and allocating buffers

### CODE REVIEW

**Comment by ceriottm** [comment]
one question would be whethere we should have a global cache (and mutex) or these static variables inside the function call are better / acceptable. no strong feelings.

**Review by frostedoyster — APPROVED** [review]

**Comment by Luthaf** [comment]
Before merging this, I would like to see some benchmarks showing the additional code complexity actually makes a difference in the run time!

**Comment by ceriottm** [comment]
Fair point. Of course this will matter most for single-point evaluations:

main:
```
**** Timings for l_max=10, n_samples=1, n_tries=10000, dtype=<class 'numpy.float64'> ****
 No derivatives:   176133.6 ns/sample ±   210027.3 (std)
Warm-up timings / sec.:
 [0.02956653 0.00033665 0.00021601 0.00020289 0.00019646]
 No derivatives, jit:    21250.1 ns/sample ±    96404.4 (std)
Warm-up timings / sec.:
 [2.13901997e-02 4.07695770e-05 1.97887421e-05 1.74045563e-05
 1.74045563e-05]
******************************************************************************
**** Timings for l_max=10, n_samples=1, n_tries=10000, dtype=<class 'numpy.float32'> ****
 No derivatives:   318842.6 ns/sample ±   449239.1 (std)
Warm-up timings / sec.:
 [0.05334806 0.00054049 0.00036287 0.00033236 0.00033402]
 No derivatives, jit:    24297.7 ns/sample ±   142685.3 (std)
Warm-up timings / sec.:
 [2.74960995e-02 7.12871552e-05 2.38418579e-05 1.95503235e-05
 2.00271606e-05]
******************************************************************************
```
and with the caching
```
**** Timings for l_max=10, n_samples=1, n_tries=10000, dtype=<class 'numpy.float64'> ****
building cache for 10
 No derivatives:   154535.5 ns/sample ±    84238.2 (std)
Warm-up timings / sec.:
 [0.03519225 0.00052285 0.00022197 0.00019693 0.00018859]
 No derivatives, jit:    10995.7 ns/sample ±    26506.2 (std)
Warm-up timings / sec.:
 [1.27654076e-02 2.55107880e-05 1.09672546e-05 9.05990601e-06
 9.29832458e-06]
******************************************************************************
**** Timings for l_max=10, n_samples=1, n_tries=10000, dtype=<class 'numpy.float32'> ****
building cache for 10
 No derivatives:   155199.5 ns/sample ±    73677.0 (std)
Warm-up timings / sec.:
 [0.03316307 0.00039434 0.00023556 0.00020313 0.00019813]
 No derivatives, jit:    10775.5 ns/sample ±    59800.5 (std)
Warm-up timings / sec.:
 [1.67512894e-02 4.45842743e-05 1.09672546e-05 9.53674316e-06
 9.29832458e-06]
******************************************************************************
```
one-sample evaluation may not be the typical use case, but a 2x speedup in this corner case seems to me worth the 10 extra lines of code

**Comment by ceriottm** [comment]
Probably not to be fixed in this PR, but looks like Hessian evaluation is 1000x more expensive than gradients

**Review by Luthaf — APPROVED** [review]

**Pull request merged**
