### PR TITLE
Raise warning for torch double backward

### PR DESCRIPTION
**Pull request by frostedoyster**
After discussing #139, @Luthaf and I came to the conclusion that we can't do much without sacrificing a lot of performance in the important case where only mixed derivatives are needed. Therefore, we're adding a warning and thoroughly documenting the potential issues that can arise

### CODE REVIEW

**Review by Luthaf — APPROVED** [review]

**Comment by Luthaf** [comment]
The changes looks good but CI failure is strange here

**Comment by ceriottm** [comment]
> The changes looks good but CI failure is strange here

Guess you'll have to test this - neither Filippo nor I have eaten from the tree of vendor lock-in

**Comment by ceriottm** [comment]
ok I reverted all my foolish attempts to fix the CI

**Comment by Luthaf** [comment]
I can not reproduce the issue locally, but I just realized that CI was still using macos-13 runner, which is x86_64. Torch is no longer supporting this architecture, so I switched to macos-14 runner, which is arm64. If this fixes CI I think we are good to go, this could be an architecture-specific bug, or a bug with older versions of torch.

**Comment by frostedoyster** [comment]
Thanks for the fix!

**Pull request merged**
