### PR TITLE
Add pickling methods to support TorchScript.

### PR DESCRIPTION
**Pull request by HapeMask**
Sphericart already uses `TORCH_LIBRARY` but when serializing the library reference into a TorchScript JIT module, the class needs a pickle/unpickle method as well.

### CODE REVIEW

**Comment by Luthaf** [comment]
Thank you for doing this! The code looks good but fails the formatting test. Could you run `clang-format` on the files you modified? Then everything should be good to go!

**Comment by HapeMask** [comment]
> Could you run clang-format on the files you modified?

Sure! I tried this quickly and it reformatted the entire file, which probably means I did something wrong. I'll look into it shortly.

**Comment by HapeMask** [comment]
> Thanks for the PR, @HapeMask! Could you share with us the exact `clang-format` command you ran (and also the directory you ran it from)? We're trying to improve our C++ formatting, perhaps I can open a PR for that

Yup, here's some info on what I ran + version:

```
]$ clang-format --version
clang-format version 16.0.1 (https://github.com/conda-forge/clangdev-feedstock 1dd6d282bc8be5828cf8c163d2c68cc525f527c5)

]$ clang-format -i sphericart-torch/src/torch.cpp
```

```
]$ git log
commit 2f07d5f (HEAD -> pickle, mine/pickle)
Author: Gabe Schwartz <gabe.schwartz@oculus.com>
Date:   Wed Oct 25 15:52:31 2023 -0700

    Add pickling methods to support TorchScript.

commit 8ffaf38 (origin/main, origin/HEAD, main)
Author: Filippo Bigi <98903385+frostedoyster@users.noreply.github.com>
Date:   Fri Aug 18 14:20:46 2023 +0200

    Fix computations for large output sizes (#67)

    * Fix large-size integer overflows on CPU
    * Allow computations on large tensors on GPU

    ---------

    Co-authored-by: Nick J. Browning <nickjbrowning@gmail.com>
    Co-authored-by: Guillaume Fraux <luthaf@luthaf.fr>

```

and this is the changeset it produced for that file: https://gist.github.com/HapeMask/31d530a691b0937344d7392eee8cc0e0

I'm happy to just copy/paste the formatting changes to only the code I added, just let me know.

**Comment by frostedoyster** [comment]
I tested clang-format-10 and clang-format-17 on main and they give the exact same results, so I would guess that version is not the issue. From the changelog that @HapeMask sent, it seems that the first indent is 2 spaces, while all others are 4 spaces. It's also reordering the includes (alphabetically) and it seems to dislike long lines. Almost as if it was operating according to a different set of formatting instructions. @Luthaf any ideas? What should we do?

**Comment by Luthaf** [comment]
What happens if you run `clang-format --style=file:$(pwd)/.clang-format -i sphericart-torch/src/torch.cpp`? I though this was the default behavior, but let's check!

**Comment by HapeMask** [comment]
Oh! I don't know how this happened but my clone of your `main` branch was from Aug. 18th (before the `.clang-format` file was added to the repo, so I didn't have that file in my branch. Re-running after merging the latest `main` branch gives better results, I'll push the changes today.

**Pull request merged**
