### PR TITLE
Julia Version Release Branch

### PR DESCRIPTION
**Pull request by cortner**
**IMPORTANT: DO NOT SQUASH-MERGE THIS BRANCH!!!**

This PR implements some fixes that are required to enable auto-merging of new Julia versions of the package into the Julia package registry. The main thing I had to do that people might be concerned about is copy the MIT license into the julia folder. The existing of the license in the root and the julia folder might cause some confusion for users. I'm not sure how to deal with this. 

If this is ok, then this PR can be merged.

### CODE REVIEW

**Comment by ceriottm** [comment]
Maybe you can make a symlink rather than a copy? Maybe that will make it clearer this is a packaging requirement and not dual licensing

**Comment by cortner** [comment]
Good idea, I can try that with the next registration.

**Review by ceriottm — APPROVED** [review]
Looks uncontroversial enough!

**Comment by Luthaf** [comment]
> IMPORTANT: DO NOT SQUASH-MERGE THIS BRANCH!!!

I rebase-merged it

**Comment by cortner** [comment]
Thank you - for future reference : I may continue to register new Julia versions from a branch and then ask to merge it again.

**Pull request merged**
